template_path: static-web.yaml

parameters:
  ArtifactsBucket: !environment_variable DEV_S3_BUCKET
  AliasName: !environment_variable DEV_URL
  ACMCertificateArn: !environment_variable CERTIFICATE_ARN
  HostedZoneId: !environment_variable HOSTED_ZONE_ID
