name: AWS Cloudformation Deployment

on:
  push:
    branches:
    - dev
    - main

env:
  TEMPLATE: template.yml
  AWS_STACK_NAME: dev-kommune-okr
  AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_REGION: eu-west-1
  HOSTED_ZONE_ID: ${{secrets.HOSTED_ZONE_ID}}
  DEV_URL: okr.dev.dcx.no
  CERTIFICATE_ARN: ${{secrets.CERTIFICATE_ARN}}
  DEV_S3_BUCKET: dev-kommune-okr

jobs:
  deploy_infra:
    name: Build and Deploy
    runs-on: self-hosted
    steps:
    # checkout this repo
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build code
      run: |
        npm install
        npm run build
    - name: Run deploy Script in dev
      if: github.ref == 'refs/heads/main'
      run: |
        cd deployment
        bash script.sh dev
    - name: Upload Artifacts to dev
      if: github.ref == 'refs/heads/main'
      run: |
        ls -al
        aws s3 cp --recursive ./build s3://dev-kommune-okr-api/
    - name: Invalidating cache in dev
      if: github.ref == 'refs/heads/main'
      run: |
        cd deployment
        bash invalidate-cache.sh dev
